services:
  emby-monitor:
    image: ghcr.io/pototazhang/emby-js:latest
    build: .
    container_name: emby-monitor
    restart: unless-stopped
    ports:
      - "8787:8787"
    environment:
      ADMIN_TOKEN: "change-me"
      PORT: "8787"
      HOST: "0.0.0.0"
      DATA_DIR: "/data"
      SCHEDULE_ENABLED: "1"
      SCHEDULE_CRON: "*/1 * * * *"
      RUN_SCHEDULE_ON_START: "0"
      DOCKER_SELF_UPDATE_ENABLED: "1"
      DOCKER_UPDATE_IMAGE: "ghcr.io/pototazhang/emby-js:latest"
    volumes:
      - ./docker-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
