name = "emby-monitor"
main = "emby.js"
compatibility_date = "2026-05-16"
workers_dev = true

[placement]
region = "aws:ap-southeast-1"

[triggers]
crons = ["*/1 * * * *"]

[[kv_namespaces]]
binding = "EMBY_DB"
id = "cea5e738f0ef4600a2e7c1f357e417e1"
