name = "emby-monitor"
main = "emby.js"
compatibility_date = "2026-05-16"
workers_dev = true

[triggers]
crons = ["*/1 * * * *"]

[[kv_namespaces]]
binding = "EMBY_DB"
id = "1f1c651cf9a44f0dbe211df04e29f564"
